import { FileText, Clock, CheckCircle2, Sparkles, TrendingUp, PieChart } from "lucide-react";

export function ReportStatsCards({ stats, loading }: { stats: any; loading: boolean }) {
  const successRate = stats?.successful_exports && stats?.total ? `${Math.round((stats.successful_exports / stats.total) * 100)}%` : "100%";
  return (
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
      <div className="bg-slate-800/50 border border-slate-700/50 rounded-xl p-4 flex items-center justify-between backdrop-blur-sm"><div><p className="text-xs font-medium text-slate-400">Total Generated</p><p className="text-2xl font-bold text-white mt-1">{loading ? "..." : (stats?.total ?? 0)}</p><span className="text-xs text-emerald-400 flex items-center gap-1 mt-1 font-medium"><TrendingUp className="w-3.5 h-3.5" />{stats?.generated_today ?? 0} today</span></div><div className="p-3 bg-blue-500/10 text-blue-400 rounded-xl border border-blue-500/20"><FileText className="w-6 h-6" /></div></div>
      <div className="bg-slate-800/50 border border-slate-700/50 rounded-xl p-4 flex items-center justify-between backdrop-blur-sm"><div><p className="text-xs font-medium text-slate-400">Scheduled Automation</p><p className="text-2xl font-bold text-white mt-1">{loading ? "..." : (stats?.scheduled ?? 0)}</p><span className="text-xs text-indigo-400 flex items-center gap-1 mt-1 font-medium"><Clock className="w-3.5 h-3.5" />{stats?.pending ?? 0} queue pending</span></div><div className="p-3 bg-indigo-500/10 text-indigo-400 rounded-xl border border-indigo-500/20"><Clock className="w-6 h-6" /></div></div>
      <div className="bg-slate-800/50 border border-slate-700/50 rounded-xl p-4 flex items-center justify-between backdrop-blur-sm"><div><p className="text-xs font-medium text-slate-400">Successful Exports</p><p className="text-2xl font-bold text-white mt-1">{loading ? "..." : (stats?.successful_exports ?? 0)}</p><span className="text-xs text-emerald-400 flex items-center gap-1 mt-1 font-medium"><CheckCircle2 className="w-3.5 h-3.5" />{successRate} rate</span></div><div className="p-3 bg-emerald-500/10 text-emerald-400 rounded-xl border border-emerald-500/20"><CheckCircle2 className="w-6 h-6" /></div></div>
      <div className="bg-slate-800/50 border border-slate-700/50 rounded-xl p-4 flex items-center justify-between backdrop-blur-sm"><div><p className="text-xs font-medium text-slate-400">Storage Consumption</p><p className="text-2xl font-bold text-white mt-1">{loading ? "..." : `${stats?.storage_usage_mb ?? 0} MB`}</p><span className="text-xs text-purple-400 flex items-center gap-1 mt-1 font-medium"><PieChart className="w-3.5 h-3.5" />{stats?.active_dashboards ?? 0} active boards</span></div><div className="p-3 bg-purple-500/10 text-purple-400 rounded-xl border border-purple-500/20"><Sparkles className="w-6 h-6" /></div></div>
    </div>
  );
}
