export const REPORTS_TAGS = [
  "Performance",
  "Document",
  "Notification",
  "AuditLog",
  "Intelligence",
  "AIModel",
  "Timeline",
  "Report",
  "WorkforceReport",
  "PerformanceReport",
  "ComplianceReport",
  "EngagementReport",
  "CultureReport",
  "HrDocument",
  "ExitDocument",
  "LetterGenerator",
  "Announcement",
] as const;
