export const API_TAGS = [
  "Auth",
  "User",
  "Company",
  "Employee",
  "Manager",
  "Department",
  "Attendance",
  "AttendanceAnalytics",
  "Leave",
  "Payroll",
  "Payslip",
  "PayrollAnalytics",
  "PayCycle",
  "SalaryProcessing",
  "SalaryStructure",
  "Overtime",
  "Bonus",
  "Deduction",
  "Reimbursement",
  "Advance",
  "BankTransfer",
  "Compliance",
  "PayrollDashboard",
  "PayrollSettings",
  "Tax",
  "SalaryComponent",
  "Allowance",
  "Template",
  "Security",
  "AiPayroll",
  "Recruitment",
  "Candidate",
  "Job",
  "Onboarding",
  "EmployeeOnboarding",
  "Performance",
  "Document",
  "Notification",
  "AuditLog",
  "Intelligence",
  "AIModel",
  "Timeline",
  "HRAdminOnboarding",
  "HRAdminWorkflow",
  "HRAdminNewHire",
  "HRAdminDocument",
  "HRAdminTask",
  "Report",
  "WorkforceReport",
  "PerformanceReport",
  "ComplianceReport",
  "EngagementReport",
  "CultureReport",
] as const;

export type ApiTagType = (typeof API_TAGS)[number];

