import { IntelligenceHubLayout } from "@/features/intelligence/components/IntelligenceHubLayout";
import { IntelligenceHubHeader } from "@/features/intelligence/components/IntelligenceHubHeader";
import { IntelligenceEmptyState } from "@/features/intelligence/components/IntelligenceEmptyState";
import { InsightSection, InsightSectionItem } from "@/features/intelligence/components/InsightSection";
import {
  Lightbulb,
  CheckCircle2,
  Users,
  BarChart3,
  Heart,
  ShieldCheck,
} from "lucide-react";

export default function AIRecommendationsPage() {
  const sections: { title: string; subtitle: string; icon: any; items: InsightSectionItem[] }[] = [
    {
      title: "Recommended Actions",
      subtitle: "Prioritized executive actions generated by NexaHR AI",
      icon: CheckCircle2,
      items: [
        {
          id: "rec-1",
          title: "Priority Action Prescriptions",
          subtitle: "Recommended Actions",
          description: "No recommendations available. AI recommendations will appear once sufficient organizational data is available.",
          icon: CheckCircle2,
        },
      ],
    },
    {
      title: "Workforce Recommendations",
      subtitle: "Strategic staffing, department balancing, and re-allocation advice",
      icon: Users,
      items: [
        {
          id: "rec-2",
          title: "Resource Allocation Recommendations",
          subtitle: "Workforce Recommendations",
          description: "No recommendations available. Workforce advisory insights require active headcount telemetry.",
          icon: Users,
        },
      ],
    },
    {
      title: "Performance Recommendations",
      subtitle: "Targeted interventions, training alignment, and goal adjustments",
      icon: BarChart3,
      items: [
        {
          id: "rec-3",
          title: "Goal & Skill Development Guidance",
          subtitle: "Performance Recommendations",
          description: "No recommendations available. Performance improvement prescriptions require performance evaluation inputs.",
          icon: BarChart3,
        },
      ],
    },
    {
      title: "Engagement Recommendations",
      subtitle: "Retention nudges, recognition ideas, and experience enhancements",
      icon: Heart,
      items: [
        {
          id: "rec-4",
          title: "Culture & Morale Boosters",
          subtitle: "Engagement Recommendations",
          description: "No recommendations available. Engagement action plans require pulse check data.",
          icon: Heart,
        },
      ],
    },
    {
      title: "Compliance Recommendations",
      subtitle: "Policy updates, audit preparations, and risk mitigations",
      icon: ShieldCheck,
      items: [
        {
          id: "rec-5",
          title: "Regulatory Gap Remedies",
          subtitle: "Compliance Recommendations",
          description: "No recommendations available. Compliance action items will synthesize when policies and audit logs are connected.",
          icon: ShieldCheck,
        },
      ],
    },
  ];

  return (
    <IntelligenceHubLayout>
      <div className="space-y-6">
        <IntelligenceHubHeader
          title="AI Recommendations"
          subtitle="Generate intelligent HR recommendations based on available organizational information."
          icon={Lightbulb}
          badgeText="Prescriptive AI"
          showBack={true}
          moduleName="AI Recommendations"
        />

        <IntelligenceEmptyState
          icon={Lightbulb}
          title="No recommendations available"
          description="AI recommendations will appear once sufficient organizational data is available. Connect data sources to trigger automated prescriptive guidance."
          actionText="Data Required"
          moduleName="AI Recommendations"
        />

        <div className="space-y-8 pt-2">
          {sections.map((section) => (
            <InsightSection
              key={section.title}
              title={section.title}
              subtitle={section.subtitle}
              icon={section.icon}
              items={section.items}
            />
          ))}
        </div>
      </div>
    </IntelligenceHubLayout>
  );
}
