import type { AICategory } from "@/types/ai/category";
import { OFC360_AI_ENGINE } from "./aiEngine";

export interface AICapability {
  id: string;
  name?: string;
  title: string;
  category: Exclude<AICategory, "ALL">;
  description: string;
  taskType?: string;
  badge: string; // Capability Status e.g. "ACTIVE", "AVAILABLE", "BETA"
  engine: "ofc360-ai";
  iconName: string;
  route?: string;
  demoPrompt?: string;
  defaultOutput?: string;
}

export const OFC360_AI_CAPABILITIES: AICapability[] = [
  // 1. Recruitment AI Capabilities
  {
    id: "recruitment-ats",
    title: "ATS Resume Screening",
    category: "Recruitment AI",
    description: "Automated resume parsing, skill extraction, and candidate ranking for high-volume hiring.",
    taskType: "resume_screening",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "FileSearch",
    route: "/recruitment/ats",
    demoPrompt: "Screen 500 resumes for Senior Engineer role",
    defaultOutput: "Screened 500 resumes. Top 10 candidates identified with 94% accuracy.",
  },
  {
    id: "recruitment-sourcing",
    title: "Talent Sourcing AI",
    category: "Recruitment AI",
    description: "Automated candidate discovery across LinkedIn, GitHub, and portfolio sites.",
    taskType: "talent_sourcing",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Search",
    route: "/recruitment/sourcing",
    demoPrompt: "Find 20 React developers in Berlin",
    defaultOutput: "Found 23 React developers in Berlin. 15 open to opportunities.",
  },
  {
    id: "recruitment-interview",
    title: "Interview Question Generator",
    category: "Recruitment AI",
    description: "Role-specific behavioral and technical interview questions with evaluation rubrics.",
    taskType: "interview_questions",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "HelpCircle",
    route: "/recruitment/interview",
    demoPrompt: "Generate interview questions for Senior DevOps",
    defaultOutput: "Generated 15 questions: 5 technical, 5 behavioral, 5 situational with rubrics.",
  },
  {
    id: "recruitment-matching",
    title: "Candidate-Job Matching",
    category: "Recruitment AI",
    description: "Semantic matching of candidate profiles to job requirements with explainable scores.",
    taskType: "candidate_matching",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Target",
    route: "/recruitment/matching",
    demoPrompt: "Match candidates to Senior Frontend role",
    defaultOutput: "Top match: 92% alignment. Key gaps: GraphQL, TypeScript.",
  },
  {
    id: "recruitment-onboarding",
    title: "Onboarding Intelligence",
    category: "Recruitment AI",
    description: "Personalized onboarding plans, buddy matching, and 30-60-90 day milestone tracking.",
    taskType: "onboarding_intelligence",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Rocket",
    route: "/recruitment/onboarding",
    demoPrompt: "Create onboarding plan for Senior Designer",
    defaultOutput: "30-60-90 day plan created with 12 milestones, 3 buddies assigned.",
  },
  {
    id: "recruitment-offers",
    title: "Offer Letter Generator",
    category: "Recruitment AI",
    description: "Dynamic offer letters with compensation breakdown, equity, benefits, and e-signature.",
    taskType: "offer_generation",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "FileCheck",
    route: "/recruitment/offers",
    demoPrompt: "Generate offer for Senior Backend at $180k",
    defaultOutput: "Offer letter generated with salary breakdown, equity grant, and benefits summary.",
  },

  // 2. Employee AI Capabilities
  {
    id: "employee-timeline",
    title: "Employee Timeline",
    category: "Employee AI",
    description: "Career milestones, promotions, awards, project anniversaries, and achievement roadmap.",
    taskType: "employee_timeline",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Clock",
    route: "/employee-experience/timeline",
    demoPrompt: "Show timeline for Alex Mercer",
    defaultOutput: "Career timeline generated: 3 promotions, 5 awards, 12 projects in 4 years.",
  },
  {
    id: "employee-visitor",
    title: "Visitor Management",
    category: "Employee AI",
    description: "Digital guest check-ins, visitor security passes, host notifications, and front-desk logs.",
    taskType: "visitor_management",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "UserCheck",
    route: "/employee-experience/visitors",
    demoPrompt: "Register visitor John Doe for 2pm meeting",
    defaultOutput: "Visitor registered. Badge printed. Host notified via Slack.",
  },
  {
    id: "employee-expenses",
    title: "Expense Claims",
    category: "Employee AI",
    description: "Submit receipts, corporate expense reimbursements, mileage tracking, and approval queues.",
    taskType: "expense_claims",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Receipt",
    route: "/employee-experience/expenses",
    demoPrompt: "Submit $150 client dinner receipt",
    defaultOutput: "Receipt scanned. Merchant: Le Bistro. Amount: $147. Submitted for approval.",
  },
  {
    id: "employee-travel",
    title: "Travel Requests",
    category: "Employee AI",
    description: "Corporate travel authorizations, flight/hotel reservations, itineraries, and per-diem.",
    taskType: "travel_requests",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Plane",
    route: "/employee-experience/travel",
    demoPrompt: "Book NYC trip for Nov 15-17",
    defaultOutput: "Flight: UA 1234. Hotel: Marriott Times Square. Per-diem: $200/day.",
  },
  {
    id: "employee-announcements",
    title: "Company Announcements",
    category: "Employee AI",
    description: "Leadership broadcasts, townhall updates, holiday notices, cultural recognitions.",
    taskType: "announcements",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Megaphone",
    route: "/employee-experience/announcements",
    demoPrompt: "Post townhall recap for Q3",
    defaultOutput: "Announcement posted. 247 employees notified via Slack and email.",
  },
  {
    id: "employee-support",
    title: "Support Help Desk",
    category: "Employee AI",
    description: "Internal IT, HR, and Operations ticketing with SLA resolutions and request tracking.",
    taskType: "helpdesk_support",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "LifeBuoy",
    route: "/employee-experience/helpdesk",
    demoPrompt: "Request VPN access for new hire",
    defaultOutput: "Ticket created: IT-2024-0042. Assigned to IT Support. SLA: 4 hours.",
  },

  // 3. Workforce & Shift AI Capabilities
  {
    id: "workforce-scheduling",
    title: "Smart Scheduling",
    category: "Workforce & Shift AI",
    description: "Auto-generate optimal shift rosters respecting labor laws, preferences, and coverage.",
    taskType: "smart_scheduling",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Calendar",
    route: "/workforce/scheduling",
    demoPrompt: "Generate November schedule for 50 nurses",
    defaultOutput: "Schedule generated. 98% preference match. 0 labor law violations.",
  },
  {
    id: "workforce-attendance",
    title: "Attendance Intelligence",
    category: "Workforce & Shift AI",
    description: "Real-time punch tracking, geo-fencing, facial verification, and anomaly detection.",
    taskType: "attendance_intelligence",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Activity",
    route: "/attendance",
    demoPrompt: "Show today's attendance for Engineering",
    defaultOutput: "42/45 present. 2 late. 1 on leave. 1 remote.",
  },
  {
    id: "workforce-leave",
    title: "Leave Management",
    category: "Workforce & Shift AI",
    description: "Automated leave balances, accrual calculations, policy enforcement, and team calendars.",
    taskType: "leave_management",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "CalendarOff",
    route: "/leave",
    demoPrompt: "Check leave balance for Sarah Chen",
    defaultOutput: "Annual: 12/18 days. Sick: 4/6 days. Casual: 2/4 days.",
  },
  {
    id: "workforce-shift",
    title: "Shift Optimization",
    category: "Workforce & Shift AI",
    description: "Demand-based shift planning, overtime minimization, and labor cost optimization.",
    taskType: "shift_optimization",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Zap",
    route: "/workforce/shifts",
    demoPrompt: "Optimize Dec schedule for 200 agents",
    defaultOutput: "Optimized schedule saves $12K/month. 15% overtime reduction.",
  },
  {
    id: "workforce-planning",
    title: "Workforce Planning",
    category: "Workforce & Shift AI",
    description: "Headcount forecasting, skill gap analysis, and succession planning.",
    taskType: "workforce_planning",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "TrendingUp",
    route: "/workforce/planning",
    demoPrompt: "Forecast Q1 2025 headcount for Sales",
    defaultOutput: "Projected: +12 hires. Budget impact: $1.2M. Start sourcing Nov 1.",
  },

  // 4. Performance & OKR AI Capabilities
  {
    id: "performance-okr",
    title: "OKR Intelligence",
    category: "Performance & OKR AI",
    description: "AI-powered OKR drafting, alignment checking, and progress forecasting.",
    taskType: "okr_intelligence",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Target",
    route: "/performance/okr",
    demoPrompt: "Draft Q1 OKRs for Engineering team",
    defaultOutput: "Drafted 3 objectives with 9 key results. Alignment score: 87%.",
  },
  {
    id: "performance-review",
    title: "Review Intelligence",
    category: "Performance & OKR AI",
    description: "Automated review cycle orchestration, calibration assistance, and bias detection.",
    taskType: "review_intelligence",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "FileCheck2",
    route: "/performance/reviews",
    demoPrompt: "Analyze Q4 review cycle for 200 employees",
    defaultOutput: "Identified 12 calibration outliers. 3 inflation cases. 2 deflation cases.",
  },
  {
    id: "performance-skills",
    title: "Skill Gap Analysis",
    category: "Performance & OKR AI",
    description: "AI-mapped skill gaps, personalized learning paths, and certification tracking.",
    taskType: "skill_gap_analysis",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Award",
    route: "/performance/skills",
    demoPrompt: "Identify skill gaps for Marketing team",
    defaultOutput: "Top gaps: Data Analytics (67%), SQL (54%), Project Mgmt (48%).",
  },
  {
    id: "performance-velocity",
    title: "Performance Velocity",
    category: "Performance & OKR AI",
    description: "Real-time goal progress, milestone forecasting, and bottleneck alerts.",
    taskType: "performance_velocity",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "TrendingUp",
    route: "/performance/velocity",
    demoPrompt: "Show Q4 velocity for Product team",
    defaultOutput: "Velocity: 87% on track. 2 objectives at risk: Launch date, User adoption.",
  },

  // 5. Payroll & Comp AI Capabilities
  {
    id: "payroll-processing",
    title: "Payroll Automation",
    category: "Payroll & Comp AI",
    description: "End-to-end payroll run, tax calculation, statutory deductions, and net pay.",
    taskType: "payroll_processing",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Calculator",
    route: "/payroll/process",
    demoPrompt: "Run November payroll for 500 employees",
    defaultOutput: "Payroll processed. Gross: $2.4M. Net: $1.7M. Tax: $480K.",
  },
  {
    id: "payroll-compliance",
    title: "Tax & Compliance",
    category: "Payroll & Comp AI",
    description: "Multi-jurisdiction tax calculation, filing deadlines, and regulatory updates.",
    taskType: "tax_compliance",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "ShieldCheck",
    route: "/payroll/compliance",
    demoPrompt: "Calculate Q4 tax for California employees",
    defaultOutput: "CA State Tax: $42K. SDI: $2.1K. UI: $1.8K. Total: $45.9K.",
  },
  {
    id: "payroll-compensation",
    title: "Compensation Planning",
    category: "Payroll & Comp AI",
    description: "Merit increase modeling, market benchmarking, equity refresh, and budget allocation.",
    taskType: "compensation_planning",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Coins",
    route: "/payroll/compensation",
    demoPrompt: "Model 4% merit increase for Engineering",
    defaultOutput: "Budget: $480K. 42 employees eligible. Avg increase: 4.2%. Equity pool: 2%.",
  },
  {
    id: "payroll-benefits",
    title: "Benefits Administration",
    category: "Payroll & Comp AI",
    description: "Open enrollment orchestration, carrier integration, COBRA, and HSA/FSA management.",
    taskType: "benefits_administration",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Heart",
    route: "/payroll/benefits",
    demoPrompt: "Run open enrollment for 2025",
    defaultOutput: "Enrollment launched. 3 plans. 89% participation target. Deadline: Dec 15.",
  },

  // 6. Compliance & Legal AI Capabilities
  {
    id: "compliance-audit",
    title: "Audit Automation",
    category: "Compliance & Legal AI",
    description: "Automated evidence collection, control testing, and audit trail generation.",
    taskType: "audit_automation",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "ShieldCheck",
    route: "/compliance/audit",
    demoPrompt: "Prepare SOC 2 Type II evidence",
    defaultOutput: "Evidence package generated: 47 controls. 23 automated. 24 manual. Ready for auditor.",
  },
  {
    id: "compliance-policy",
    title: "Policy Management",
    category: "Compliance & Legal AI",
    description: "Policy lifecycle, acknowledgment tracking, version control, and regulatory mapping.",
    taskType: "policy_management",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "FileCheck",
    route: "/compliance/policy",
    demoPrompt: "Distribute updated Data Privacy Policy",
    defaultOutput: "Policy distributed to 1,247 employees. 94% acknowledged in 48h.",
  },
  {
    id: "compliance-risk",
    title: "Risk Intelligence",
    category: "Compliance & Legal AI",
    description: "Automated risk assessments, control gap analysis, and regulatory change monitoring.",
    taskType: "risk_intelligence",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "AlertTriangle",
    route: "/compliance/risk",
    demoPrompt: "Assess GDPR compliance risk for EU expansion",
    defaultOutput: "Risk score: 72/100. Gaps: DPA (3), DPIA (2), SCC (1). Remediation plan attached.",
  },
  {
    id: "compliance-legal",
    title: "Legal Document AI",
    category: "Compliance & Legal AI",
    description: "Contract review, clause extraction, obligation tracking, and redline assistance.",
    taskType: "legal_document_ai",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "FileSignature",
    route: "/compliance/legal",
    demoPrompt: "Review 50-page SaaS agreement",
    defaultOutput: "Reviewed 47 clauses. 3 high-risk: Liability cap, IP ownership, Termination. 2 medium-risk.",
  },

  // 7. Document Gen AI Capabilities
  {
    id: "doc-gen-offer",
    title: "Offer Letter Generator",
    category: "Document Gen AI",
    description: "Dynamic offer letters with compensation breakdown, equity, benefits, and e-signature.",
    taskType: "doc_offer_generator",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "FilePlus",
    route: "/documents/offer",
    demoPrompt: "Generate offer for Senior PM at $160k",
    defaultOutput: "Offer generated: $155k base, 10% bonus, 5k RSU. PDF ready for e-sign.",
  },
  {
    id: "doc-gen-experience",
    title: "Experience Certificate",
    category: "Document Gen AI",
    description: "Employment verification, relieving letters, salary certificates, and NOCs.",
    taskType: "doc_experience_certificate",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "FileText",
    route: "/documents/experience",
    demoPrompt: "Generate experience letter for John Doe",
    defaultOutput: "Experience certificate generated. 3 years tenure. Relieved Oct 15. Good standing.",
  },
  {
    id: "doc-gen-verification",
    title: "Verification Letters",
    category: "Document Gen AI",
    description: "Employment verification, salary certificates, visa support, and bank letters.",
    taskType: "doc_verification_letters",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "FileCheck",
    route: "/documents/verification",
    demoPrompt: "Generate salary verification for visa",
    defaultOutput: "Verification letter generated. CTC: $145k. Employer: OFC360. Valid 90 days.",
  },
  {
    id: "doc-gen-noc",
    title: "NOC Generator",
    category: "Document Gen AI",
    description: "No Objection Certificates for passport, visa, higher studies, and side projects.",
    taskType: "doc_noc_generator",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "FileText",
    route: "/documents/noc",
    demoPrompt: "Generate NOC for passport renewal",
    defaultOutput: "NOC generated. Valid 90 days. HR signed. Reference: NOC/2024/045.",
  },
  {
    id: "doc-gen-contract",
    title: "Contract Generator",
    category: "Document Gen AI",
    description: "Employment contracts, NDAs, consultant agreements, and vendor contracts.",
    taskType: "doc_contract_generator",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "FileSignature",
    route: "/documents/contracts",
    demoPrompt: "Generate NDA for vendor partnership",
    defaultOutput: "Mutual NDA generated. Term: 2 years. Jurisdiction: Delaware. Auto-expiry: 2 years.",
  },
  {
    id: "doc-gen-policy",
    title: "Policy Document Gen",
    category: "Document Gen AI",
    description: "HR policy creation, employee handbook updates, and compliance documentation.",
    taskType: "doc_policy_generator",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "ScrollText",
    route: "/documents/policy",
    demoPrompt: "Create Remote Work Policy v2.0",
    defaultOutput: "Policy drafted: Hybrid model (3/2). Equipment stipend: $500/yr. Security requirements attached.",
  },

  // 8. Meeting Intelligence AI Capabilities
  {
    id: "meeting-transcript",
    title: "Meeting Transcription",
    category: "Meeting Intelligence AI",
    description: "Real-time transcription, speaker diarization, and searchable meeting archives.",
    taskType: "meeting_transcription",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Mic",
    route: "/meetings/transcribe",
    demoPrompt: "Transcribe 45-min board meeting",
    defaultOutput: "Transcribed 4,200 words. 4 speakers. 98% accuracy. Action items: 7.",
  },
  {
    id: "meeting-summary",
    title: "Meeting Summarization",
    category: "Meeting Intelligence AI",
    description: "AI-generated summaries, action items, decisions, and follow-up tracking.",
    taskType: "meeting_summarization",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "FileText",
    route: "/meetings/summarize",
    demoPrompt: "Summarize yesterday's sprint review",
    defaultOutput: "Summary: 3 stories done. 1 blocked. Velocity: 34 pts. Action items: 3.",
  },
  {
    id: "meeting-insights",
    title: "Meeting Analytics",
    category: "Meeting Intelligence AI",
    description: "Meeting load analysis, participation equity, recurring meeting audit, and ROI.",
    taskType: "meeting_analytics",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "BarChart3",
    route: "/meetings/analytics",
    demoPrompt: "Analyze October meeting load for Engineering",
    defaultOutput: "42 meetings. 18 hrs. 3 redundant. Potential savings: 6 hrs/week.",
  },
  {
    id: "meeting-action",
    title: "Action Item Tracker",
    category: "Meeting Intelligence AI",
    description: "Automatic action item extraction, owner assignment, due dates, and completion tracking.",
    taskType: "meeting_action_items",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "CheckSquare",
    route: "/meetings/actions",
    demoPrompt: "Extract actions from yesterday's standup",
    defaultOutput: "Extracted 4 actions. 2 assigned to Alex. 1 to Priya. 1 to team. Due: Fri.",
  },
  {
    id: "meeting-scheduling",
    title: "Smart Scheduling",
    category: "Meeting Intelligence AI",
    description: "AI-powered scheduling, timezone optimization, conflict resolution, and room booking.",
    taskType: "meeting_scheduling",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Calendar",
    route: "/meetings/schedule",
    demoPrompt: "Schedule sync for 8 people across 3 timezones",
    defaultOutput: "Optimal slot: Wed 14:00 UTC. Conflicts: 0. Room: Conference A booked.",
  },

  // 9. Analytics & Predictive AI Capabilities
  {
    id: "analytics-workforce",
    title: "Workforce Analytics",
    category: "Analytics & Predictive AI",
    description: "Headcount trends, turnover prediction, diversity metrics, and organizational health.",
    taskType: "workforce_analytics",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "PieChart",
    route: "/analytics/workforce",
    demoPrompt: "Show 2024 workforce trends",
    defaultOutput: "Headcount: +12% YoY. Turnover: 11.2%. Diversity: 42% women in tech.",
  },
  {
    id: "analytics-predictive",
    title: "Predictive Workforce",
    category: "Analytics & Predictive AI",
    description: "Headcount forecasting, attrition risk modeling, hiring demand, and capacity planning.",
    taskType: "predictive_workforce",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "TrendingUp",
    route: "/analytics/predictive",
    demoPrompt: "Forecast Q1 2025 attrition",
    defaultOutput: "Predicted attrition: 9.4%. Top risk: Senior Engineers (18%). Retention actions: 5.",
  },
  {
    id: "analytics-people",
    title: "People Analytics",
    category: "Analytics & Predictive AI",
    description: "Organizational network analysis, influence mapping, collaboration patterns, and silo detection.",
    taskType: "people_analytics",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Users",
    route: "/analytics/people",
    demoPrompt: "Map collaboration network for Product org",
    defaultOutput: "Network density: 0.34. 3 silos detected. Bridge nodes: 4. Key connectors: 7.",
  },
  {
    id: "analytics-financial",
    title: "Financial Workforce Analytics",
    category: "Analytics & Predictive AI",
    description: "Labor cost analysis, revenue per employee, compensation benchmarking, and ROI modeling.",
    taskType: "financial_workforce",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "Calculator",
    route: "/analytics/financial",
    demoPrompt: "Calculate revenue per employee by department",
    defaultOutput: "Eng: $420k. Sales: $890k. Marketing: $310k. Ops: $180k. Avg: $450k.",
  },

  // 10. Knowledge & RAG AI Capabilities
  {
    id: "rag-policy",
    title: "Policy RAG Assistant",
    category: "Knowledge & RAG AI",
    description: "Natural language queries over employee handbook, policies, and compliance docs.",
    taskType: "policy_rag",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "BookOpen",
    route: "/knowledge/policy",
    demoPrompt: "What is the parental leave policy?",
    defaultOutput: "Parental leave: 16 weeks paid (100% first 8 weeks, 60% next 8). Eligibility: 12 months tenure.",
  },
  {
    id: "rag-technical",
    title: "Technical Knowledge RAG",
    category: "Knowledge & RAG AI",
    description: "Codebase Q&A, architecture docs, API references, and debugging assistance.",
    taskType: "technical_rag",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "FileCode",
    route: "/knowledge/technical",
    demoPrompt: "How to configure Redis cache in production?",
    defaultOutput: "Use REDIS_URL env var. Enable TLS. Max memory: 2GB. Eviction: allkeys-lru.",
  },
  {
    id: "rag-hr",
    title: "HR Knowledge Assistant",
    category: "Knowledge & RAG AI",
    description: "Employee self-service for benefits, leave, payroll, and policy questions.",
    taskType: "hr_rag",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "HelpCircle",
    route: "/knowledge/hr",
    demoPrompt: "How do I apply for parental leave?",
    defaultOutput: "Submit request via HR portal 30 days prior. Required: Medical cert, 30-day notice. Paid: 16 weeks.",
  },
  {
    id: "rag-code",
    title: "Code Generation AI",
    category: "Knowledge & RAG AI",
    description: "Boilerplate generation, test generation, refactoring suggestions, and migration assistance.",
    taskType: "code_generation",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "FileCode",
    route: "/knowledge/code",
    demoPrompt: "Generate React hook for API pagination",
    defaultOutput: "Generated usePagination hook with TypeScript. Includes loading, error, retry logic.",
  },

  // 11. Biometrics & Vision AI Capabilities
  {
    id: "vision-face",
    title: "Face Attendance",
    category: "Biometrics & Vision AI",
    description: "Liveness detection, anti-spoofing, geo-fencing, and multi-factor attendance.",
    taskType: "face_attendance",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "ScanFace",
    route: "/attendance/face",
    demoPrompt: "Verify face check-in for Employee EMP-101",
    defaultOutput: "Liveness: PASS. Anti-spoof: PASS. Geo-fence: WITHIN. Status: CHECKED_IN.",
  },
  {
    id: "vision-document",
    title: "Document OCR",
    category: "Biometrics & Vision AI",
    description: "Invoice extraction, receipt parsing, contract digitization, and form processing.",
    taskType: "document_ocr",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "FileSearch",
    route: "/vision/ocr",
    demoPrompt: "Extract data from 50 invoices",
    defaultOutput: "Processed 50 invoices. Accuracy: 96.2%. Extracted: vendor, amount, date, line items.",
  },
  {
    id: "vision-id",
    title: "ID Verification",
    category: "Biometrics & Vision AI",
    description: "Passport, driver's license, and national ID verification with fraud detection.",
    taskType: "id_verification",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "ShieldAlert",
    route: "/vision/id",
    demoPrompt: "Verify passport for new hire",
    defaultOutput: "Passport valid. MRZ check: PASS. Face match: 99.2%. Fraud signals: NONE.",
  },
  {
    id: "vision-badge",
    title: "Badge Recognition",
    category: "Biometrics & Vision AI",
    description: "Employee badge detection, access control integration, and tailgating alerts.",
    taskType: "badge_recognition",
    badge: "ACTIVE",
    engine: "ofc360-ai",
    iconName: "BadgeCheck",
    route: "/vision/badge",
    demoPrompt: "Detect badge in lobby camera feed",
    defaultOutput: "Badge detected: EMP-1042. Access: GRANTED. Zone: Engineering Floor. Confidence: 99.8%.",
  },
];

export function getAICapabilities(): AICapability[] {
  return OFC360_AI_CAPABILITIES;
}

export function getAICapabilityById(id: string): AICapability | undefined {
  return OFC360_AI_CAPABILITIES.find((c) => c.id === id);
}

export function getAICapabilitiesByCategory(category: Exclude<AICategory, "ALL">): AICapability[] {
  return OFC360_AI_CAPABILITIES.filter((c) => c.category === category);
}

// Canonical Engine & Backward-Compatible Aliases
export { OFC360_AI_ENGINE };
export const ALL_71_AI_MODELS: AICapability[] = OFC360_AI_CAPABILITIES;
export type AIToolItem = AICapability;
