import {
  LayoutDashboard, Users, Clock,
  FileText, Building2, ShieldCheck,
  Heart, BarChart3, Target,
  Boxes, Settings, Globe, Award, Key, Zap, FileCode2, Server, Cpu, Lock,
  MessageSquare, Sparkles, BrainCircuit, UserPlus, GraduationCap,
  CreditCard, Video, ScanFace, Calendar, FileSpreadsheet,
  CheckSquare
} from "lucide-react";
import { NavSearchItem } from "./searchTypes";

export const NAVIGATION_SEARCH_ITEMS: NavSearchItem[] = [
  // Core HR & Dashboard
  {
    id: "nav-dashboard",
    title: "Dashboard",
    category: "pages",
    section: "Core HR",
    path: "/dashboard",
    icon: LayoutDashboard,
    keywords: ["home", "overview", "analytics", "stats", "main"],
  },
  {
    id: "nav-people",
    title: "People Directory",
    category: "pages",
    section: "Workforce",
    path: "/people",
    icon: Users,
    keywords: ["employees", "staff", "directory", "team", "workers", "roster", "list"],
  },
  {
    id: "nav-managers",
    title: "Managers Directory",
    category: "pages",
    section: "Workforce",
    path: "/people/managers",
    icon: Users,
    keywords: ["leads", "managers", "supervisors", "department heads"],
  },
  {
    id: "nav-attendance",
    title: "Attendance & Timesheets",
    category: "pages",
    section: "Core HR",
    path: "/attendance",
    icon: Clock,
    keywords: ["clock in", "clock out", "time tracking", "leave", "shifts", "presence"],
  },
  {
    id: "nav-ai-face-attendance",
    title: "AI Face Attendance",
    category: "pages",
    section: "Core HR",
    path: "/attendance/ai-face",
    icon: ScanFace,
    keywords: ["facial recognition", "biometrics", "kiosk", "scan", "check-in"],
  },
  {
    id: "nav-payroll",
    title: "Payroll & Compensation",
    category: "pages",
    section: "Finance & HR",
    path: "/payroll",
    icon: CreditCard,
    keywords: ["salary", "payslip", "wages", "tax", "deductions", "bonus", "earnings"],
  },
  {
    id: "nav-reports",
    title: "Reports & Analytics",
    category: "pages",
    section: "Core HR",
    path: "/reports",
    icon: BarChart3,
    keywords: ["metrics", "charts", "export", "headcount", "performance", "turnover"],
  },

  // AI & Intelligence
  {
    id: "nav-intelligence",
    title: "AI Intelligence Hub",
    category: "pages",
    section: "AI & Innovation",
    path: "/intelligence",
    icon: BrainCircuit,
    keywords: ["artificial intelligence", "models", "insights", "automation", "predictive"],
  },
  {
    id: "nav-ai-recruiter",
    title: "AI Recruiter & Sourcing",
    category: "pages",
    section: "AI & Innovation",
    path: "/intelligence/ai-recruiter",
    icon: Sparkles,
    keywords: ["sourcing", "screening", "interviews", "hiring bot", "candidates"],
  },
  {
    id: "nav-ai-workforce",
    title: "AI Workforce Intelligence",
    category: "pages",
    section: "AI & Innovation",
    path: "/intelligence/ai-workforce",
    icon: Users,
    keywords: ["capacity", "skills matrix", "planning", "allocation"],
  },
  {
    id: "nav-ai-ops",
    title: "AI Operations",
    category: "pages",
    section: "AI & Innovation",
    path: "/intelligence/ai-ops",
    icon: Cpu,
    keywords: ["workflows", "pipelines", "automation", "ops"],
  },

  // Talent & Recruitment
  {
    id: "nav-talent-intelligence",
    title: "Talent Intelligence & ATS",
    category: "pages",
    section: "Recruitment",
    path: "/talent-intelligence",
    icon: Target,
    keywords: ["recruitment", "candidates", "applicant tracking", "job openings", "resumes", "ats score"],
  },
  {
    id: "nav-resource-intelligence",
    title: "Resource Intelligence & Assets",
    category: "pages",
    section: "Operations",
    path: "/resource-intelligence",
    icon: Boxes,
    keywords: ["assets", "inventory", "laptops", "hardware", "office gear", "licenses"],
  },
  {
    id: "nav-employee-experience",
    title: "Employee Experience & Engagement",
    category: "pages",
    section: "Experience",
    path: "/employee-experience",
    icon: Globe,
    keywords: ["culture", "satisfaction", "timeline", "recognition", "milestones"],
  },

  // Connect & Collaboration
  {
    id: "nav-connect",
    title: "Connect Workspace & Chat",
    category: "pages",
    section: "Collaboration",
    path: "/connect",
    icon: MessageSquare,
    keywords: ["chat", "direct message", "channel", "colleagues", "conversations"],
  },
  {
    id: "nav-connect-calls",
    title: "Connect Video Calls & Meetings",
    category: "pages",
    section: "Collaboration",
    path: "/connect/calls",
    icon: Video,
    keywords: ["video call", "meeting", "screen share", "huddle", "conference"],
  },

  // Settings & Admin
  {
    id: "nav-settings",
    title: "Settings & Configuration",
    category: "pages",
    section: "Administration",
    path: "/settings",
    icon: Settings,
    keywords: ["preferences", "profile", "account", "theme", "security", "config"],
  },
  {
    id: "nav-settings-billing",
    title: "Billing & Subscriptions",
    category: "pages",
    section: "Administration",
    path: "/settings/billing",
    icon: CreditCard,
    keywords: ["invoices", "plans", "pricing", "payment method", "receipts"],
  },

  // IT Admin & Super Admin
  {
    id: "nav-it-sso",
    title: "IT Admin SSO & SAML",
    category: "pages",
    section: "IT Administration",
    path: "/it-admin/sso",
    icon: Key,
    keywords: ["single sign on", "okta", "google auth", "identity", "saml", "oidc"],
  },
  {
    id: "nav-it-access",
    title: "Access Control & Roles",
    category: "pages",
    section: "IT Administration",
    path: "/it-admin/access",
    icon: ShieldCheck,
    keywords: ["permissions", "rbac", "security groups", "privileges"],
  },
  {
    id: "nav-it-security",
    title: "IT Admin Security & Audit",
    category: "pages",
    section: "IT Administration",
    path: "/it-admin/security",
    icon: Lock,
    keywords: ["logs", "threats", "ip whitelist", "2fa", "compliance"],
  },
  {
    id: "nav-superadmin",
    title: "Super Admin Control Center",
    category: "pages",
    section: "Super Admin",
    path: "/super-admin",
    icon: Building2,
    keywords: ["multi-tenant", "tenants", "organizations", "platform", "system health"],
  },

  // Employee Self-Service
  {
    id: "nav-emp-leaves",
    title: "My Leaves & Holidays",
    category: "pages",
    section: "Employee Portal",
    path: "/employee/leave",
    icon: Clock,
    keywords: ["time off", "vacation", "sick leave", "balance", "apply leave"],
  },
  {
    id: "nav-emp-payslips",
    title: "My Payslips",
    category: "pages",
    section: "Employee Portal",
    path: "/employee/payslips",
    icon: FileText,
    keywords: ["salary slips", "download payslip", "tax statement", "form 16"],
  },
  {
    id: "nav-emp-documents",
    title: "My Documents Vault",
    category: "pages",
    section: "Employee Portal",
    path: "/employee/documents",
    icon: FileText,
    keywords: ["contracts", "id proof", "certificates", "offer letter"],
  },
  {
    id: "nav-emp-helpdesk",
    title: "Helpdesk & Support Tickets",
    category: "pages",
    section: "Support",
    path: "/employee/helpdesk",
    icon: GraduationCap,
    keywords: ["support", "tickets", "requests", "issues", "assistance"],
  },
];
