import { baseApi } from './baseApi';
import { ApiResponse } from '@/types/api';
export const payrollApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    createV2PayrollRuns: builder.mutation<ApiResponse<any>, any>({ query: (data) => ({ url: `/api/v2/payroll/runs`, method: 'POST', body: typeof data === 'object' ? data : undefined }), invalidatesTags: ['Payroll'] }),
    createV2PayrollRunsRunIdProcess: builder.mutation<ApiResponse<any>, any>({ query: (data) => ({ url: typeof data === 'string' || typeof data === 'number' ? `/api/v2/payroll/runs/${data}/process` : '/api/v2/payroll/runs/{run_id}/process', method: 'POST', body: typeof data === 'object' ? data : undefined }), invalidatesTags: ['Payroll'] }),
    createV2PayrollRunsRunIdApprove: builder.mutation<ApiResponse<any>, any>({ query: (data) => ({ url: typeof data === 'string' || typeof data === 'number' ? `/api/v2/payroll/runs/${data}/approve` : '/api/v2/payroll/runs/{run_id}/approve', method: 'POST', body: typeof data === 'object' ? data : undefined }), invalidatesTags: ['Payroll'] }),
    createV2PayrollRunsRunIdPay: builder.mutation<ApiResponse<any>, any>({ query: (data) => ({ url: typeof data === 'string' || typeof data === 'number' ? `/api/v2/payroll/runs/${data}/pay` : '/api/v2/payroll/runs/{run_id}/pay', method: 'POST', body: typeof data === 'object' ? data : undefined }), invalidatesTags: ['Payroll'] }),
    createV2PayrollRunsRunIdAnomalies: builder.mutation<ApiResponse<any>, any>({ query: (data) => ({ url: typeof data === 'string' || typeof data === 'number' ? `/api/v2/payroll/runs/${data}/anomalies` : '/api/v2/payroll/runs/{run_id}/anomalies', method: 'POST', body: typeof data === 'object' ? data : undefined }), invalidatesTags: ['Payroll'] }),
    createV2CompensationBenchmarks: builder.mutation<ApiResponse<any>, any>({ query: (data) => ({ url: `/api/v2/compensation/benchmarks`, method: 'POST', body: typeof data === 'object' ? data : undefined }), invalidatesTags: ['Payroll'] }),
    createV2CompensationRecommendationsEmployeeId: builder.mutation<ApiResponse<any>, any>({ query: (data) => ({ url: typeof data === 'string' || typeof data === 'number' ? `/api/v2/compensation/recommendations/${data}` : '/api/v2/compensation/recommendations/{employee_id}', method: 'POST', body: typeof data === 'object' ? data : undefined }), invalidatesTags: ['Payroll'] }),
  }),
});
export const { useCreateV2PayrollRunsMutation, useCreateV2PayrollRunsRunIdProcessMutation, useCreateV2PayrollRunsRunIdApproveMutation, useCreateV2PayrollRunsRunIdPayMutation, useCreateV2PayrollRunsRunIdAnomaliesMutation, useCreateV2CompensationBenchmarksMutation, useCreateV2CompensationRecommendationsEmployeeIdMutation } = payrollApi;