import React, { useState } from "react";
import {
  FileCheck,
  Sparkles,
  Download,
  CheckCircle2,
  AlertCircle,
  RefreshCw,
  Search,
  UserX,
  FileText,
  Building2,
} from "lucide-react";
import {
  useGetExitDocumentsQuery,
  useGenerateExitDocumentsMutation,
} from "../exitDocumentsApi";

interface ExitDocumentsPanelProps {
  initialExitId?: string;
}

export const ExitDocumentsPanel: React.FC<ExitDocumentsPanelProps> = ({
  initialExitId = "EXIT-9012",
}) => {
  const [exitIdInput, setExitIdInput] = useState(initialExitId);
  const [activeExitId, setActiveExitId] = useState(initialExitId);
  const [notes, setNotes] = useState("");

  const {
    data: exitDocsRes,
    isLoading: isLoadingDocs,
    isError,
    refetch,
  } = useGetExitDocumentsQuery(activeExitId, {
    skip: !activeExitId,
  });

  const [generateExitDocs, { isLoading: isGenerating }] =
    useGenerateExitDocumentsMutation();

  const [message, setMessage] = useState<{ type: "success" | "error"; text: string } | null>(null);

  const handleFetchDocs = (e: React.FormEvent) => {
    e.preventDefault();
    if (exitIdInput.trim()) {
      setActiveExitId(exitIdInput.trim());
      setMessage(null);
    }
  };

  const handleGenerate = async () => {
    if (!activeExitId) return;
    try {
      const res = await generateExitDocs({
        exitId: activeExitId,
        notes: notes || "Generated by HR Offboarding System",
      }).unwrap();

      setMessage({
        type: "success",
        text: res.message || "Experience & Relieving Certificate documents generated successfully!",
      });
    } catch (err: any) {
      setMessage({
        type: "error",
        text: err?.data?.message || "Failed to generate exit documents.",
      });
    }
  };

  const docsData = exitDocsRes?.data;

  return (
    <div className="w-full bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-sm space-y-6">
      {/* Panel Header */}
      <div className="flex items-center justify-between flex-wrap gap-4 border-b border-slate-100 dark:border-slate-800 pb-4">
        <div className="flex items-center gap-3">
          <div className="p-3 rounded-xl bg-emerald-50 dark:bg-emerald-950/60 border border-emerald-200 dark:border-emerald-800 text-emerald-600 dark:text-emerald-400">
            <UserX className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="px-2 py-0.5 rounded text-[10px] font-bold tracking-wide uppercase bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300 border border-emerald-300 dark:border-emerald-800">
                REAL GENERATOR ENDPOINT
              </span>
              <span className="text-xs text-slate-500 font-mono">/api/v1/exits/{activeExitId}/generate-documents</span>
            </div>
            <h3 className="text-xl font-bold text-slate-900 dark:text-slate-100 mt-0.5">
              Experience & Relieving Certificate Generator
            </h3>
          </div>
        </div>

        <button
          onClick={() => refetch()}
          disabled={isLoadingDocs}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${isLoadingDocs ? "animate-spin" : ""}`} />
          Refresh Status
        </button>
      </div>

      {/* Exit Request Selector Form */}
      <form onSubmit={handleFetchDocs} className="flex items-end gap-3 flex-wrap">
        <div className="flex-1 min-w-[240px]">
          <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">
            Exit / Offboarding Request ID
          </label>
          <div className="relative">
            <input
              type="text"
              value={exitIdInput}
              onChange={(e) => setExitIdInput(e.target.value)}
              placeholder="e.g. EXIT-9012"
              className="w-full pl-9 pr-3 py-2 text-sm rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-emerald-500 outline-none"
            />
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
          </div>
        </div>

        <button
          type="submit"
          className="px-4 py-2 rounded-lg text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-white transition-all"
        >
          Load Exit Documents
        </button>
      </form>

      {/* Feedback Message */}
      {message && (
        <div
          className={`p-3 rounded-lg border text-xs flex items-center gap-2 ${
            message.type === "success"
              ? "bg-emerald-50 dark:bg-emerald-950/50 border-emerald-300 text-emerald-700 dark:text-emerald-300"
              : "bg-red-50 dark:bg-red-950/50 border-red-300 text-red-700 dark:text-red-300"
          }`}
        >
          {message.type === "success" ? (
            <CheckCircle2 className="w-4 h-4 text-emerald-500" />
          ) : (
            <AlertCircle className="w-4 h-4 text-red-500" />
          )}
          {message.text}
        </div>
      )}

      {/* Generation Control Panel */}
      <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 space-y-3">
        <h4 className="text-sm font-semibold text-slate-900 dark:text-slate-100 flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-500" /> Generate Certificate Suite
        </h4>
        <p className="text-xs text-slate-500">
          Clicking generate triggers the real backend pipeline to fill employee exit details, calculate tenure, and output Relieving Letter + Experience Certificate.
        </p>

        <div className="flex items-center gap-3 pt-2">
          <input
            type="text"
            placeholder="Optional generation notes..."
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            className="flex-1 px-3 py-1.5 text-xs rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-100 outline-none"
          />
          <button
            onClick={handleGenerate}
            disabled={isGenerating || !activeExitId}
            className="flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold bg-emerald-600 hover:bg-emerald-700 text-white shadow-sm disabled:opacity-50 transition-all"
          >
            <Sparkles className="w-3.5 h-3.5" />
            {isGenerating ? "Generating Documents..." : "Generate Relieving & Experience Letters"}
          </button>
        </div>
      </div>

      {/* Generated Documents View */}
      <div>
        <h4 className="text-sm font-semibold text-slate-900 dark:text-slate-100 mb-3">
          Generated Document Files ({activeExitId})
        </h4>

        {isLoadingDocs ? (
          <div className="p-8 text-center text-xs text-slate-500 flex items-center justify-center gap-2">
            <RefreshCw className="w-4 h-4 animate-spin text-emerald-500" /> Loading exit documents...
          </div>
        ) : docsData ? (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* Relieving Letter */}
            <div className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 space-y-3">
              <div className="flex items-center justify-between">
                <FileCheck className="w-5 h-5 text-emerald-500" />
                <span className="px-2 py-0.5 rounded text-[10px] font-medium bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">
                  Ready
                </span>
              </div>
              <div>
                <h5 className="text-xs font-bold text-slate-900 dark:text-slate-100">Relieving Letter</h5>
                <p className="text-[11px] text-slate-500 mt-0.5">Official company release proof</p>
              </div>
              <a
                href={docsData.relieving_letter_url || "#"}
                target="_blank"
                rel="noreferrer"
                className="w-full flex items-center justify-center gap-1.5 py-1.5 rounded-lg text-xs font-semibold bg-slate-100 dark:bg-slate-800 hover:bg-emerald-50 dark:hover:bg-emerald-950 text-slate-700 dark:text-slate-200 hover:text-emerald-600 transition-all border border-slate-200 dark:border-slate-700"
              >
                <Download className="w-3.5 h-3.5" /> Download PDF
              </a>
            </div>

            {/* Experience Certificate */}
            <div className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 space-y-3">
              <div className="flex items-center justify-between">
                <FileText className="w-5 h-5 text-indigo-500" />
                <span className="px-2 py-0.5 rounded text-[10px] font-medium bg-indigo-100 text-indigo-800 dark:bg-indigo-950 dark:text-indigo-300">
                  Ready
                </span>
              </div>
              <div>
                <h5 className="text-xs font-bold text-slate-900 dark:text-slate-100">Experience Certificate</h5>
                <p className="text-[11px] text-slate-500 mt-0.5">Tenure & conduct summary</p>
              </div>
              <a
                href={docsData.experience_certificate_url || "#"}
                target="_blank"
                rel="noreferrer"
                className="w-full flex items-center justify-center gap-1.5 py-1.5 rounded-lg text-xs font-semibold bg-slate-100 dark:bg-slate-800 hover:bg-indigo-50 dark:hover:bg-indigo-950 text-slate-700 dark:text-slate-200 hover:text-indigo-600 transition-all border border-slate-200 dark:border-slate-700"
              >
                <Download className="w-3.5 h-3.5" /> Download PDF
              </a>
            </div>

            {/* Final Settlement Letter */}
            <div className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 space-y-3">
              <div className="flex items-center justify-between">
                <Building2 className="w-5 h-5 text-amber-500" />
                <span className="px-2 py-0.5 rounded text-[10px] font-medium bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300">
                  Ready
                </span>
              </div>
              <div>
                <h5 className="text-xs font-bold text-slate-900 dark:text-slate-100">Final Settlement Letter</h5>
                <p className="text-[11px] text-slate-500 mt-0.5">FnF breakdown statement</p>
              </div>
              <a
                href={docsData.final_settlement_letter_url || "#"}
                target="_blank"
                rel="noreferrer"
                className="w-full flex items-center justify-center gap-1.5 py-1.5 rounded-lg text-xs font-semibold bg-slate-100 dark:bg-slate-800 hover:bg-amber-50 dark:hover:bg-amber-950 text-slate-700 dark:text-slate-200 hover:text-amber-600 transition-all border border-slate-200 dark:border-slate-700"
              >
                <Download className="w-3.5 h-3.5" /> Download PDF
              </a>
            </div>
          </div>
        ) : (
          <div className="p-6 rounded-xl border border-dashed border-slate-300 dark:border-slate-800 text-center space-y-2">
            <p className="text-xs text-slate-500">
              No exit documents generated yet for exit ID <code>{activeExitId}</code>.
            </p>
            <button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="px-3 py-1.5 rounded-lg text-xs font-medium text-emerald-600 dark:text-emerald-400 hover:underline"
            >
              Click here to trigger document generation
            </button>
          </div>
        )}
      </div>
    </div>
  );
};